/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qlsxsqtxvelzgoqszvbz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsc3hzcXR4dmVsemdvcXN6dmJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgzOTUxNDUsImV4cCI6MjA5Mzk3MTE0NX0.-Wim371157f3Niiz9zDj-8Zslmo_j2BQQs8mS_CnTRk"